login/urls.py
from django.conf.urls import url
from django.conf.urls import include 
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^employee/$', views.employee_detail, name='employee_detail'),
    url(r'^logout/$' , views.logout_view, name='logout'),
    url(r'signup/$' , views.admin_signup,name='signup'),
    url(r'^home/$',views.dashboard,name='dashboard')
]

mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'', include('login.urls')),
    url(r'', include('payroll.urls')),
    url(r'', include('company.urls')),
    url(r'', include('attendance.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^employee/list$', views.employee_list, name='employee_list'),
    url(r'^employee/(?P<pk>\d+)/$', views.employee_detail, name='employee_detail'),
    url(r'^employee/new/$', views.employee_new, name='employee_new'),
    url(r'^employee/(?P<pk>\d+)/edit/$', views.employee_edit, name='employee_edit'),
    url(r'^admin/detail/$', views.admin_edit, name='admin_detail'),
    url(r'^employee/add/$', views.add_employee, name='add_employee'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate')
]

user/models.py
import decimal
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Employee(models.Model):
    '''
    Employee model stores all the details of employee required for Payroll System
 
    '''
    company = models.ForeignKey('company.Company',
                                 null=True,
                                 blank=True
                                )
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                null=True
                                )
    
    name = models.CharField(max_length = 50,null=True)
    address = models.TextField()
    phone_regex = RegexValidator(regex = r'^\+?1?\d{9,15}$',
                                 message = "Phone number must be entered in format :'+999999999'. "
                                )
    contact = models.CharField(validators = [phone_regex],
                               max_length = 17
                              )
    alter_Contact = models.CharField(validators = [phone_regex],
                                     max_length=17
                                    )
    emailid = models.EmailField(null=True)
    office_emailid = models.EmailField(null=True,blank=True)
    GENDER_CHOICES = (('M', 'Male'),
                      ('F', 'Female'),
                     )
    gender = models.CharField(max_length = 20,
                              choices = GENDER_CHOICES,
                              default = "Select"
                             )
    Dob = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to = 'payroll',
                                    default = 'None/no-img.jpeg'
    )
    joining_date = models.DateField(blank = True,
                                    null = True
                                   )
    job_type = models.CharField(max_length = 15,
                                blank = True,
                                null=True
                               )
    job_location = models.CharField(max_length = 50,
                                    blank = True,
                                    null=True
                                   )
    probation_period = models.IntegerField(blank = True,
                                           null=True
                                          )
    is_admin = models.BooleanField(default=False)


        
    def __str__(self):
        return str(self.user)


    
class Designation_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    designation = models.ForeignKey('company.Designation',
                                  blank = True,
                                  null = True
                                 )
    date = models.DateField()
    
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.designation.designation+" " +str(self.employee)

    
class Department_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    department = models.ForeignKey('company.Department',
                                 blank = True,
                                 null = True
                                )
    date = models.DateField()

    def publish(self):
        self.save()

    def __str__(self):
        return self.department.department


    
class Job_Type_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    job_type = models.ForeignKey('company.Job_Type',
                                 blank = True,
                                 null = True
                                )
    date=models.DateField()

    def publish(self):
        self.save()

    def __str__(self):
        return self.job_type.jobtype


class Leave_History(models.Model):
    
    '''
    Leave_History records total leaves taken by an employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
    )
    work_type = models.ForeignKey("company.Work_Type",
                                  blank = True,
                                  null = True
    )
    attendance = models.ForeignKey("attendance.Attendance",
                                   blank = True,
                                   null = True
    )
    leave_type = models.CharField(max_length = 200,
                                  default = "None"
    )
    date=models.DateField()
   
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.employee.name+"Leave History"

    
class Salary_History(models.Model):
    '''
    Salary_History records Salary details of an employee
    '''
    employee = models.ForeignKey(Employee,
                                 related_name = '+',
                                 blank = True,
                                 null = True
                                )
    date = models.DateField()                           
    basic_percentage = models.FloatField(default = 35)
    hra_percentage = models.FloatField(default = 40)
    conveyance_allowance = models.IntegerField(default = 1600)
    proffessional_tax = models.IntegerField(default = 200)
    income_tax = models.IntegerField(default = 0)
    
    def publish(self):
        self.save()

class Salary_Increment(models.Model):
    '''
    Salary_Increment records salary-increment details of an employee
    '''
    date = models.DateField()
    employee = models.ForeignKey(Employee,
                                 related_name = '+',
                                 blank = True,
                                 null = True
                                )
    salary = models.DecimalField(max_digits = 10,
                               decimal_places = 3,
                                 default = decimal.Decimal('0000000.000'),
                                 blank=True
                              
                              )
    effective_from = models.DateField(blank=True)
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.employee.user.username+" "+str(self.effective_from)

login/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User



class LoginForm(forms.ModelForm):
    class Meta:
        
        model = User
        fields = ('username','password')
    
    def clean(self):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')
        # user = authenticate(username=username, password=password)

        # if user is None:
        #     raise forms.ValidationError('Invalid Credentials')
        # self.cleaned_data['username'] = user
        # self.user_obj=user
        
                    
            
class DateInput(forms.DateInput):
    input_type = 'date'

login/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate,login as user_login,logout
from django.shortcuts import redirect
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from payroll.models import Salary
from company.models import Designation
from .forms import LoginForm
from user.forms import UserForm
from  user.forms import EmployeeForm
from company.forms import CompanyForm
from django.contrib.auth.models import User
from user.models import Employee, Designation_History
from company.views import company_homepage
from django.db import transaction
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
import datetime
import calendar
from django.db.models import Sum
# Create your views here.


@login_required(login_url = "login")
def index(request):
    return render(request,'login/home.html')
@login_required(login_url = "login")
def dashboard(request):

    now = datetime.datetime.now().date()
    l=[]
    l.append(0)
    for i in range(1,13):
        start_date = datetime.datetime.strptime(str(now.year)+str(i),"%Y%m")
        end_date = datetime.datetime.strptime(
            str(start_date.year)+str(i)+str(calendar.monthrange(start_date.year,start_date.month)[1]),
            "%Y%m%d"
        )
        total = Salary.objects.filter(date__gte=start_date,date__lte=end_date).aggregate(Sum('net_salary'))
        if total['net_salary__sum']==None:
            l.append(0)
        else:
            l.append(int(total['net_salary__sum']))

    #try for pie chart :)
    d = list(Designation.objects.filter(company_id=request.user.employee.company_id).values('designation'))
    l2=[]
    for i in d:
        l2.append(i['designation'])

    empdictlist = list(Employee.objects.filter(company_id=request.user.employee.company_id).values('id'))
    employees=[]
    for i in empdictlist:
        employees.append(i['id'])
    
    l3=[]
    for i in l2:
        temp=0
        for j in employees:
            latest_des_id = Designation_History.objects.filter(employee_id=j).latest('id').designation_id
            des = list(Designation.objects.filter(id=latest_des_id).values('designation'))
            des = des[0]['designation']
            if i == des:
                temp+=1
        l3.append(temp)
                


    #todays birthday try :)
    birthday_emp = Employee.objects.filter(company_id=request.user.employee.company_id,Dob__month=now.month,Dob__day=now.day)
    # for emp in birthday_emp:
    #     user_id = emp.user_id
    #     mail_address = get_object_or_404(User, id=user_id).email 
    #     print("emp : ",emp,"   user_id : ",user_id,"  email : ",mail_address)


    #male female ratio
    males = Employee.objects.filter(company_id=request.user.employee.company_id,gender="M").count()
    females = Employee.objects.filter(company_id=request.user.employee.company_id,gender="F").count()
    
    return render(request,'login/dashboard.html',
                  {
                      "a1":l[1],
                      "a2":l[2],
                      "a3":l[3],
                      "a4":l[4],
                      "a5":l[5],
                      "a6":l[6],
                      "a7":l[7],
                      "a8":l[8],
                      "a9":l[9],
                      "a10":l[10],
                      "a11":l[11],
                      "a12":l[12],
                      "l2":l2,
                      "l3":l3,
                      "birthday_emp":birthday_emp,
                      "males":males,
                      "females":females,
                  }
    )





@transaction.atomic
def admin_signup(request):
    if request.user.is_authenticated:
        return redirect('company_homepage')
    else:
        if request.method == "POST":
            userform = UserForm(request.POST)
            employeeform = EmployeeForm(request.POST,request.FILES)
            companyform = CompanyForm(request.POST,request.FILES)
            print('companyform',companyform.errors)
            print('userform',userform.errors)
            print('employeeform',employeeform.errors)
            if  userform.is_valid() and employeeform.is_valid() and companyform.is_valid() :
                
                company=companyform.save(commit=False)
                company.logo = request.FILES['logo']
                company.save()
                company.refresh_from_db()
                user = userform.save(commit=False)
                user.is_staff=True
                user.save()
                user.refresh_from_db()  # This will load the Employee created by the Signal
                employeeform = EmployeeForm(request.POST)
                #print('employeeform',employeeform)
                employeeform.full_clean()
                employee=employeeform.save(commit=False)
                employee.profile_pic = request.FILES['profile_pic']
                employee.is_admin = True
                employee.company=company
                employee.user=user
                employee.save()
                messages.success(request, 'SignUp Successful !')
                return redirect(login)
        else:
            userform = UserForm()
            employeeform = EmployeeForm(prefix='employee')
            companyform = CompanyForm(prefix='company')
        return render (request,'login/signup.html',{'companyform':companyform,
                                               'userform':userform ,
                                               'employeeform':employeeform
                                                
                                                }
                  )
        
def employee_detail(request):
    return render(request,'login/employee_detail.html')

def login(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method == "POST":
            form=LoginForm(request.POST)
            if form.is_valid():
                
                user = authenticate(username=request.POST['username'], password=request.POST['password'])
                if user is not None:
                    
                    user_login(request,user)
                    record=Employee.objects.get(user=user,is_admin=True)
                    # if record:
                    #     request.session['is_admin']=True
                    #     request.session['company']=record.company
                
                    messages.success(request, 'Admin Login Successful !')
                    if user.is_staff and user.employee.is_admin:
                        return redirect('company_homepage')
                else:
                    messages.success(request, 'Incorrect Username or Password!')
                        
                    # else:
                    #     messages.success(request, 'Employee Login Successful !')
                    #     return redirect('employee_detail')
                    
            else:
                messages.success(request, 'Invalid Credentials.')
                return redirect('login')       
    return render(request,'login/login.html',{})

def logout_view(request):
    logout(request)
    messages.success(request,'Logout Successful !')
    return redirect('index')

login/templates/login/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Payroll</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'dist/css/bootstrap.min.css' %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static 'css/app.css' %} rel="stylesheet">
  </head>

  <body>
      <nav class="navbar navbar-dark  bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Payrollz</a>

      <!--input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" -->
<ul class=list-inline>
      <li class="list-inline-item">

                {%include 'login/messages.html' %}
        </li>

        <li class="list-inline-item">
        <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign up</a>
        </li></ul>
        </li>
      </ul>
    </nav>








<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
            <div class="row">
                <div class="col-6">
                    <h1 class="logo">
                        <a href="#">

                            Sign Up
                            {% if user.is_authenticated %}
                            {% if user.is_teacher %}
                            <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                            {% else %}
                            <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                            {% endif %}
                            {% endif %}
                        </a>
                    </h1>
                </div>
                <div class="col-6 text-right">
                    {% if user.is_authenticated %}
                    <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                    <!-- <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a> -->
                    {% endif %}
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(function () {
    $('[data-toggle="tooltip"]').tooltip();
    })
</script>
            <footer>
                <a href="#">© 2017-2018</a>

            </footer>
  </body>
  </html>

login/templates/login/signup.html
{% extends 'login/base.html'  %}
{% block content %}

<form method="POST" enctype="multipart/form-data" class="employee-form">{% csrf_token %}



    <div class ="row justify-content-center">
        <!--div class="col"-->
        <div class="form-group">
            <div class="alert alert-light m-auto" role="alert">Company Detail :</div>
            <!--label for="id_deductions" style=" font-size: 1rem;">Deduction :</label-->
            <!--/div--></div></div>


            <!-- <div class="row">
                 <div class="col">
                 <div class="form-group">

                 {{companyform.as_p}}


                 </div>
                 </div>
                 </div> -->


            <!-- <div class="row">
                 <div class="col">
                 <div class="form-group">
                 <div class="alert-danger">
                 {{ companyform.errors.as_text }}
                 {{ companyform.non_field_errors }}
                 </div>
                 </div>
                 </div>
                 </div> -->

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <div class="alert-danger">
                            {{ companyform.name.errors.as_text }}
                         </div>
                        {{ companyform.name.label_tag }}
                        {{ companyform.name }}
                    </div>
                </div>

                <div class="col">
                    <div class="form-group">
                        {{ companyform.logo.errors }}
                        {{ companyform.logo.label_tag }}
                        {{ companyform.logo }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ companyform.address_line_1.errors }}
                        {{ companyform.address_line_1.label_tag }}
                        {{ companyform.address_line_1 }}
                    </div>
                </div>

                <div class="col">
                    <div class="form-group">
                        {{ companyform.address_line_2.errors }}
                        {{ companyform.address_line_2.label_tag }}
                        {{ companyform.address_line_2 }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ companyform.state.errors }}
                        {{ companyform.state.label_tag }}
                        {{ companyform.state }}
                    </div>
                </div>

                <div class="col">
                    <div class="form-group">
                        {{ companyform.postal_code.errors }}
                        {{ companyform.postal_code.label_tag }}
                        {{ companyform.postal_code }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ companyform.country.errors }}
                        {{ companyform.country.label_tag }}
                        {{companyform.country }}
                    </div>
                </div>

                <div class="col">
                    <div class="form-group">
                        {{ companyform.fax.errors }}
                        {{ companyform.fax.label_tag }}
                        {{ companyform.fax }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <div class="alert-danger">
                            {{ companyform.website.errors.as_text }}
                        </div>
                        {{ companyform.website.label_tag }}
                        {{ companyform.website }}
                    </div>

                </div>
            </div>




            <div class ="row justify-content-center">
                <!--div class="col"-->
                <div class="form-group">
                    <div class="alert alert-light m-auto" role="alert">Admin Personal Detail :</div>
                    <!--label for="id_deductions" style=" font-size: 1rem;">Deduction :</label-->
                    <!--/div--></div></div>


                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                {{ employeeform.name.errors }}
                                {{ employeeform.name.label_tag }}
                                {{ employeeform.name }}

                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col">

                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.address.errors }}-->
                                {{ employeeform.address.label_tag }}
                                {{ employeeform.address}}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.profile_pic.errors }}-->
                                {{ employeeform.profile_pic.label_tag }}
                                {{ employeeform.profile_pic}}
                                                </div></div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <!--{{ form.contact.errors }}-->
                                {{ employeeform.contact.label_tag }}
                                {{ employeeform.contact}}
                            </div>
                        </div>



                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.alter_Contact.errors }}-->
                                {{ employeeform.alter_Contact.label_tag }}
                                {{ employeeform.alter_Contact}}
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.Dob.errors }}-->
                                {{ employeeform.Dob.label_tag }}
                                {{ employeeform.Dob}}
                            </div>
                        </div>



                         <div class="col">
                            <div class="form-group">
                                <!-- {{ form.emailid.errors }}-->
                                {{ employeeform.emailid.label_tag }}
                                {{ employeeform.emailid}}
                            </div>
                         </div>

                         <div class="col">
                            <div class="form-group">
                                <!-- {{ form.emailid.errors }}-->
                                <label for="id_office_emailid">Office Email Address:</label>
                                {{ employeeform.office_emailid}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.gender.errors }}-->
                                {{ employeeform.gender.label_tag }}
                                {{ employeeform.gender}}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <!-- {{ form.joining_date.errors }}-->
                                {{ employeeform.joining_date.label_tag }}
                                {{employeeform.joining_date}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <!-- {{ form.salary.errors }}-->
                                {{employeeform.salary.label_tag }}
                                {{ employeeform.salary}}
                            </div>
                            <div class="col"></div>
                        </div>
                    </div>




<div class ="row justify-content-center">
                <!--div class="col"-->
                <div class="form-group">
                    <div class="alert alert-light m-auto" role="alert">Login Credentials :</div>
                    <!--label for="id_deductions" style=" font-size: 1rem;">Deduction :</label-->
                    <!--/div--></div></div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                {% if userform.username.errors%}
                                <div class="alert alert-success">
                                    {{ userform.username.errors }}
                                </div>
                                {% endif %}
                                {{ userform.username.label_tag }}
                                {{ userform.username }}

                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                               <div class="alert-light"> {{ userform.password1.errors }}</div>
                                {{ userform.password1.label_tag }}
                                {{ userform.password1 }}

                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <div class="alert-danger"> {{ userform.password2.errors }}</div>
                                {{ userform.password2.label_tag }}
                                {{ userform.password2 }}


                            </div>
                        </div>
                    </div>


<div class ="row justify-content-center">
                    <button type="submit" class="btn btn-primary btn-md" name="btnCompany">Submit</button></div>
</form>
                    {% endblock %}