attendance/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
           url(r'^attendance/$',views.new_mark_attendance,name='mark_attendance'),
           url(r'^attendance/(?P<pk>\d+)/$',views.mark_attendance,name='mark_attendance'),
           url(r'^attendance/view/$',views.view_attendance_employee,name='view_attendance'),
           url(r'^leave-application/$',views.leave_application,name='leave_application'),
           url(r'^attendance/view/company/$',views.view_attendance_company,name='view_attendance_company'),
    
           
]

        

mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'', include('login.urls')),
    url(r'', include('payroll.urls')),
    url(r'', include('company.urls')),
    url(r'', include('attendance.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^employee/list$', views.employee_list, name='employee_list'),
    url(r'^employee/(?P<pk>\d+)/$', views.employee_detail, name='employee_detail'),
    url(r'^employee/new/$', views.employee_new, name='employee_new'),
    url(r'^employee/(?P<pk>\d+)/edit/$', views.employee_edit, name='employee_edit'),
    url(r'^admin/detail/$', views.admin_edit, name='admin_detail'),
    url(r'^employee/add/$', views.add_employee, name='add_employee'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate')
]

attendance/models.py
from django.db import models


class Attendance(models.Model):
    '''
    Attendance modules marks attendance per day for an employee
    '''
    employee = models.ForeignKey('user.Employee',
                                 blank = True,
                                 null = True
                                )
    work_type = models.ForeignKey('company.Work_Type',
                                   blank = True,
                                   null = True
                                 )
    date = models.DateField()
    MARK_CHOICES = ((1,'Present'),
                  (0.5,'Halfday'),
                  (0,'Absent'),
                 )
    mark = models.IntegerField(choices = MARK_CHOICES,
                               blank=False,default=1
                              )
    LEAVE_CHOICES = (('Privilege Leave','Privilege Leave'),
                   ('Casual Leave','Casual Leave'),
                  )
    leave_type = models.CharField(max_length = 15,
                                  choices = LEAVE_CHOICES,
                                  blank = True
                               )
    remPrivilegeLeave=models.IntegerField(null=True,blank=True)
    remCasualLeave=models.IntegerField(null=True,blank=True)
    pl=models.IntegerField(default=0)
    cl=models.IntegerField(default=0)
    lop=models.BooleanField(default=False)
    def publish(self):
        self.save()

    def __str__(self):
        return str(self.employee.user.username)+str(self.date) + " " + str(self.mark)
 

class Leave_Application(models.Model):
    '''
    Leave_Application models record leave application by employees
    '''
    employee = models.ForeignKey('user.Employee',
                                  blank = True,
                                  null = True
                                 )
    work_type = models.ForeignKey('company.Work_Type',
                                  blank = True,
                                  null = True
                                 )
    leave_from = models.DateField()
    leave_to = models.DateField()
    LEAVE_CHOICES = (('Privilege Leave','Privilege Leave'),
                   ('Casual Leave','Casual Leave'),
                  )
    leave_type = models.CharField(max_length = 200,choices=LEAVE_CHOICES)
    
    REMARK_CHOICES=(('S','Sanctioned'),('NS','Not Sanctioned'))
    remark=models.CharField(max_length = 200,choices=REMARK_CHOICES,blank=True, null=True)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.employee.user.username + " " + str(self.leave_from) + "-" + str(self.leave_to)

attendance/views.py
from django.shortcuts import render
from company.models import Holiday
from .models import Attendance,Leave_Application
from .forms import AttendanceForm, ViewAttendanceForm
from .forms import LeaveApplicationForm, ViewAttendanceCompanyForm
from user.forms import EmployeeForm
from user.models import Designation_History,Employee
from user.views import employee_detail
from company.models import Designation
from django.shortcuts import render,get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib import messages
from django.utils import timezone
from django.db.models import Count
from django.forms import formset_factory
from django.forms import modelformset_factory
from django.core.paginator import Paginator,PageNotAnInteger
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def new_mark_attendance(request):
    
    company=request.user.employee.company
    emp_count=Employee.objects.filter(company=company)
    print('emp_count',emp_count)
    data=[{
        'employee':emp
          }for emp in emp_count]
    
    AttendanceFormSet= formset_factory(AttendanceForm,max_num=1,can_order=True,can_delete=True)
    if request.method=="POST":
        form=ViewAttendanceCompanyForm(request.POST)
        Attendance_FormSet=AttendanceFormSet(request.POST)
        #attendance_form=AttendanceForm(request.POST)
        
        if Attendance_FormSet.is_valid():
            #attendance=Attendance_FormSet.save(commit=False)
            print('errors',Attendance_FormSet.errors)
            
            new_records=[]
            date=datetime.datetime.strptime(request.POST['monthdate'], "%Y-%m-%d")
            holiday=Holiday.objects.filter(date=date).exists()
            
            if not holiday and not date.weekday() == 5 and not date.weekday() == 6:

                for attendance_form in Attendance_FormSet:
                    print('attendance_Form',attendance_form)
                        

                    print('attendance',attendance_form.cleaned_data.get('employee'))
                    employee=attendance_form.cleaned_data.get('employee')
                    print('date & employee',date,employee)
                    attendance_exist=Attendance.objects.filter(employee=employee,date=date).exists()
                    print('attendance_Exist',attendance_exist)
                    if not attendance_exist:
                        print('employee',employee.pk)
                        date=request.POST['monthdate']
                        print(date)
                        mark=attendance_form.cleaned_data.get('mark')
                        print(mark)
                        leave_type=attendance_form.cleaned_data.get('leave_type')
                        print('leave-type',leave_type)
                        try:
                            last_record=Attendance.objects.filter(employee = employee.pk).latest('id')
                            print('last_Record',last_record)
                        except ObjectDoesNotExist:
                            last_record = None
                            print('last_Record',last_record)
                        try:
                        
                            dsgn=Designation_History.objects.filter(employee=employee.pk).latest('id')
                            print('dsgn-pl',dsgn.designation.privilege_leave)
                            if last_record: 
                                remPrivilegeLeave = last_record.remPrivilegeLeave
                                remCasualLeave = last_record.remCasualLeave
                                pl = last_record.pl
                                cl = last_record.cl
                                lop= last_record.lop
                                print('rempl',remPrivilegeLeave)
                        
                            else:
                                
                                remPrivilegeLeave = dsgn.designation.privilege_leave
                                remCasualLeave = dsgn.designation.casual_leave
                                pl=0
                                cl=0
                                lop=False
                                
                            if mark == 0 and leave_type =='Privilege Leave':
                                if last_record:
                                    if last_record.pl: 
                                        if last_record.pl>=dsgn.designation.privilege_leave:
                                            if last_record.cl<dsgn.designation.casual_leave:
                                                pl=last_record.pl
                                                cl=last_record.cl + 1
                                                remPrivilegeLeave = last_record.remPrivilegeLeave
                                                remCasualLeave = dsgn.designation.casual_leave - cl
                                            else:
                                                pl=last_record.pl
                                                cl=last_record.cl
                                                remPrivilegeLeave = last_record.remPrivilegeLeave
                                                remCasualLeave = last_record.remCasualLeave
                                                lop = True
                                        else:
                                            pl=last_record.pl + 1
                                            remPrivilegeLeave = dsgn.designation.privilege_leave - pl
                                            remCasualLeave = last_record.remCasualLeave
                                    
                                            if last_record.cl:
                                                cl=last_record.cl
                                   
                                    else:
                                        pl+=1
                                        remPrivilegeLeave = dsgn.designation.privilege_leave - pl
                                        remCasualLeave = last_record.remCasualLeave
                                        cl = last_record.cl
                    
                                else:
                                    pl+=1
                                    remPrivilegeLeave = dsgn.designation.privilege_leave - pl
                                    print('cl',dsgn.designation.casual_leave)
                                    remCasualLeave = dsgn.designation.casual_leave
                            
                           
                            if mark == 0 and leave_type=='Casual Leave':
                                if last_record:
                                    if last_record.cl:
                                        if last_record.cl >= dsgn.designation.casual_leave:
                                            if last_record.pl < dsgn.designation.privilege_leave:
                                                pl=last_record.pl + 1
                                                cl=last_record.cl
                                                remPrivilegeLeave = dsgn.designation.privilege_leave - pl
                                                remCasualLeave = last_record.remCasualLeave
                                            else:
                                                lop = True
                                                pl=last_record.pl
                                                cl=last_record.cl
                                                remPrivilegeLeave = last_record.remPrivilegeLeave
                                                remCasualLeave = last_record.remCasualLeave
                            
                                        else:
                                            cl=last_record.cl + 1
                                            remCasualLeave = dsgn.designation.casual_leave - cl
                                            remPrivilegeLeave = last_record.remPrivilegeLeave 
                                            if last_record.pl:
                                                pl=last_record.pl
                                    else:
                                        cl+=1
                                        remCasualLeave = dsgn.designation.casual_leave - cl
                                        remPrivilegeLeave = last_record.remPrivilegeLeave
                                        pl = last_record.pl 
                                else:
                                    cl+=1
                                    remCasualLeave = dsgn.designation.casual_leave - cl
                                    remPrivilegeLeave = dsgn.designation.privilege_leave

                                
                    
                            print('employee',employee)
                            print('date',date)
                            print('mark',mark)
                            print('leave_Type',leave_type)
                            print('remPrivilegeLeave',remPrivilegeLeave)
                            print('remCasualLeave',remCasualLeave)
                            print('pl',pl)
                            print('cl',cl)
                            print('lop',lop)
                            # if not lop:
                            #     lop=False
                        
                            new_records.append(Attendance(
                                employee=employee,
                                date=date,
                                mark=mark,
                                leave_type=leave_type,
                                remPrivilegeLeave=remPrivilegeLeave,
                                remCasualLeave=remCasualLeave,
                                pl=pl,
                                cl=cl,

attendance/templates/attendance/attendance_detail.html
{% extends 'attendance/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1> Attendance Report</h1>
</div>
<div class="col-sm-7">
    <!-- {% for message in messages %}
         < <div class="alert alert-success">
         <a class="close" href="#" data-dismiss="alert">×</a>

         {{ message }}

         </div>
          {% endfor %}>
       -->
            <div class="table-responsive-sm">
                <table class="table table-sm">
                    <tr>
                        <td style="width: 16.66%"><strong>Date</strong></td>
                        <td><strong>Employee</strong></td>
                        <td ><strong>Mark</strong></td>
                        <td ><strong>leavetype<strong></td>
                        <td ><strong>PL</strong></td>
                        <td ><strong>CL</strong></td>

                    </tr>

                    {% for obj in records %}
                    <tr>
                        <td style="width: 16.66%">{{obj.date}}</td>
                        <td>{{obj.employee}}</td>
                        <td >{{obj.mark}}</td>
                        {% ifequal obj.leave_type "" %}
                             <td><p>None</p></td>
                             {% else %}
                        <td >{{obj.leave_type}}</td>
                        {% endifequal %}
                        <td >{{obj.remPrivilegeLeave}}</td>
                        <td>{{obj.remCasualLeave}}</td>

                    </tr>

                    {% endfor %}
                </table>
            </div>



            {% endblock  %}

attendance/templates/attendance/base.html
{% load staticfiles %}


<!doctype html>
<html lang="en">
    <head>





        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ request.user.employee.company.logo.url}}">

        <title>Payroll For {{ request.user.employee.company.name }}     </title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'company/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
        <!-- Custom styles for this template -->
        <link href="{% static 'css/payroll.css' %}" rel="stylesheet">

                                <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/        GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


                 <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>

<script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"> </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> </script>


    </head>

    <body>





        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">


            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
                <img src="{{request.user.employee.company.logo.url}}" width="30" height="30" class="d-inline-block align-left" alt="">
                {% if user.is_authenticated %}
                {{ request.user.employee.company.name }}
                {% endif  %}
            </a>

            <!--
                 <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"></a> -->
            <!-- {{ request.session.company }} -->
            <!--input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"-->
            <ul class="navbar-nav px-3 ">
                <li class="nav-item text-nowrap">


                    {% if user.is_authenticated %}
                    <p class="pt-3 nav-link active d-inline ">Logged in as <strong class="alert">{{ request.user.username }}</strong> <a class="nav-link" href="{% url 'logout' %}">Sign out</a></p>

                    {% endif  %}
                </li>

            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">

                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'dashboard' %}">
                                    <span data-feather="home"></span>
                                    Dashboard <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link " href="{% url 'employee_detail' pk=request.user.employee.pk  %}">
                                    <span data-feather="user"></span>
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link " href="{% url 'edit_company'  %}">
                                    <span data-feather="home"></span>
                                    Company
                                </a>
                            </li>
<li class="nav-item">
                                <a class="nav-link " href="{% url 'employee_list'  %}">
                                    <span data-feather="users"></span>
                                    Employee<span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'mark_attendance' %}">
                                    <span data-feather="edit"></span>
                                    Attendance
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'salary_employee_list'  %}">
                                    <span data-feather="dollar-sign"></span>
                                    Salary
                                </a>
                            </li>

                        </ul>


                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                        {% block content %}
                        {% endblock %}

             </form>
                    </div>
            </div>



            <!-- Icons -->
                 <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

            <script>
                feather.replace()
$('.dropdown-toggle').dropdown()
            </script>


 <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
                 <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>



            <script>
             $('#leave_type').hide();


             $(document).ready(function() {
                 $('select[name = "mark"]').change(function(){

                     if ($(this).val() == "0"){
                         $('div#leave_type').show();
                     }

                     if ($(this).val() == "1"){
                         $('div#leave_type').hide();
                     }

                     if ($(this).val() == "0.5"){
                         $('div#leave_type').hide();
                     }
                 });
             });

            </script>



   </body>

</html>

attendance/templates/attendance/leave_application.html
{% extends 'attendance/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Mark Attendance</h1>


</div>

<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}

    <form method="POST" class="employee-form">{% csrf_token %}
        <div class="row">
            <div class="col">
                {{form.as_p}}
                <button type="submit" class="btn btn-primary btn-sm" name="btnCompany">Submit</button>

            </div>
            <div class="col">
                <h6><strong>Leave Balance:</strong><h6>
                <div class="table-responsive-sm border">
                    <table class="table table-sm">
                        <tr class="table-active">
                            <td ><strong>PL</strong></td>
                            <td ><strong>CL</strong></td>

                        </tr>
                        <tr class="table">
                            <td>{{leave.remPrivilegeLeave}}</td>
                            <td>{{leave.remCasualLeave}}</td>
                        </tr>

                </div>


            </div>
        </div>

        {% endblock %}

attendance/templates/attendance/leaveapplication_detail.html
{% extends 'attendance/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Leave Application</h1>


</div>

     <div class="col-sm-7">
         <!-- {% for message in messages %}
              <div class="alert alert-success">
              <a class="close" href="#" data-dismiss="alert">×</a>

              {{ message }}
            -->
     </div>
    {% endfor %}

    <div class="table-responsive-sm">
        <div class="row">
            <div class="col-8">
        <table class="table table-sm">
            <tr>
                <td><strong>Employee</strong></td>
                <td ><strong>Leave From</strong></td>
                <td ><strong>Leave To<strong></td>
                <td ><strong>Leave Type</strong></td>
                <td ><strong>Remark</strong></td>

            </tr>
            {% for lv in leaveapplication %}
            <tr>
                <td>{{lv.employee}}</strong></td>
                <td >{{lv.leave_from}}</strong></td>
                <td >{{lv.leave_to}}<strong></td>
                <td >{{lv.leave_type}}</strong></td>
                <td ><strong>{{lv.get_remark_display}}</strong></td>

            </tr>


                    {% endfor %}
                </table>
            </div>
</div>
<div class="row">
            <div class="col-4">
                <h6><strong>Leave Balance:</strong><h6>
                <div class="table-responsive-sm border">
                    <table class="table table-sm">
                        <tr class="table-active">
                            <td ><strong>PL</strong></td>
                            <td ><strong>CL</strong></td>

                        </tr>
                         {% for lv in leave %}
                        <tr class="table">
                            <td>{{lv.remPrivilegeLeave}}</td>
                            <td>{{lv.remCasualLeave}}</td>
                        </tr>
 {% endfor %}
                </div>

</div>
            </div>

            {% endblock  %}

attendance/templates/attendance/mark_attendance.html
{% extends 'attendance/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Mark Attendance</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">



     <li class="nav-item">
     <a class="nav-link" href="{% url 'view_attendance'  %}">View Attendance</a>
     </li>

     <li class="nav-item">
     <a class="nav-link" href="{% url 'view_attendance_company'  %}">View Attendance Company</a>
     </li>
    </ul>
    </div>

</div>



<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}




    <form method="POST" class="employee-form">{% csrf_token %}

        <div class="row">
            <div class="col">
                <div class="form-group">
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    {{ form.employee.errors }}
                    {{ form.employee.label_tag }}
                    {{ form.employee }}
                </div>
            </div>

            <div class="col">
                <div class="form-group">
                    {{ form.date.errors }}
                    {{ form.date.label_tag }}
                    {{ form.date }}
                </div>
            </div>
        </div>
        <div class="row">
        <div class="col">
                <div class="form-group">
                    {{ form.mark.errors }}
                    {{ form.mark.label_tag }}
                    {{ form.mark }}
                </div>
        </div>


        <div class="col">
                <div class="form-group">
                    {{ form.work_type.errors }}
                    {{ form.work_type.label_tag }}
                    {{ form.work_type }}
                </div>
        </div>
        </div>

        <div class ="row">
            <div class="col-6">
                <div class="form-group">
                    <div id="leave_type">
                        {{ form.leave_type.errors }}
                        {{ form.leave_type.label_tag }}
                        {{ form.leave_type }}
                    </div>
                </div>
            </div>
        </div>
<button type="submit" class="btn btn-primary btn-sm" name="btnAttendance">Mark</button>

</form>

<!-- <div class="mt-5 "> -->

{% if record %}
<div class="row">
    <div class="col mt-5">

        <!-- <div id="table-scroll" class="table-scroll mt-5">
             <div class="table-wrap">
             <!--table class="main-table"-->

        <!--table  class=" main-table table table-md table-responsive table-wrap" > -->
                    <div class="table-responsive-sm">
                <table class="table table-sm table-striped" style="border-collapse:separate">
                <thead class="thead-dark">
                    <tr>


                        <th class="fixed-side" scope="col">Employee</th>
                        <!-- <th  scope="col">Department</th>
                             <th  scope="col">Designation</th>
                             <th  scope="col">Job-Type</th> -->
                        <th  scope="col">Mark</th>

                        <th  scope="col">Leave-Type</th>

                        <th  scope="col">PL</th>
                        <th  scope="col">CL</th>


                    </tr>
                </thead>
                <tbody>

                    {% for attendance in record %}
                    <tr>
                        <td><a class="fixed-side text-info font-weight-bold " href="{% url 'employee_detail' pk=attendance.employee_id  %}">{{attendance.employee.user.username}}</a></td>
                        <!-- <td></td>
                             <td></td>
                             <td></td> -->
                        <td>{{attendance.mark}}</td>
                        {%if attendance.leave_type%}
                        <td>{{attendance.leave_type}}</td>
                        {%else%}
                        <td>None</td>
                        {% endif%}
                        <td>{{attendance.remPrivilegeLeave}}</td>
                        <td>{{attendance.remCasualLeave}}</td>
                    </tr>
                    {% endfor  %}

                </tbody>
            </table>
    </div>
</div>
    </div>

{%else%}
<h6 class="alert-info text-center">No attendance has been marked for today.</h6>
{%endif%}



{% endblock %}