company/urls.py
from django.conf.urls import url
from company import views
import login

urlpatterns = [
           url(r'^company/$',views.edit_company,name='edit_company'),
           url(r'^holiday/$',views.add_holiday,name='add_holiday'),
           url(r'^work-type/$',views.add_worktype,name='add_worktype'),
           url(r'^designation/$',views.add_designation,name='add_designation'),
           url(r'^department/$',views.add_department,name='add_department'),
           url(r'^job-type/$',views.add_jobtype,name='add_jobtype'),
           url(r'^holiday/detail/$',views.holiday_detail,name='holiday_detail'),
           url(r'^holiday/(?P<pk>\d+)/$',views.holiday_delete,name='holiday_delete'),
           url(r'^work-type/detail/$',views.worktype_detail,name='worktype_detail'),
           url(r'^work-type/(?P<pk>\d+)/$',views.worktype_delete,name='worktype_delete'),
       url(r'^job-type/detail/$',views.jobtype_detail,name='jobtype_detail'),
       url(r'^job-type/(?P<pk>\d+)/$',views.jobtype_delete,name='jobtype_delete'),
    url(r'^department/detail/$',views.department_detail,name='department_detail'),
    url(r'^department/(?P<pk>\d+)/$',views.department_delete,name='department_delete'),
   
        url(r'^designation/detail/$',views.designation_detail,name='designation_detail'),
         url(r'^designation/(?P<pk>\d+)/$',views.designation_delete,name='designation_delete'),
       # url(r'^company/home/$',login.views.dashboard,name='company_homepage')
    
]

mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'', include('login.urls')),
    url(r'', include('payroll.urls')),
    url(r'', include('company.urls')),
    url(r'', include('attendance.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^employee/list$', views.employee_list, name='employee_list'),
    url(r'^employee/(?P<pk>\d+)/$', views.employee_detail, name='employee_detail'),
    url(r'^employee/new/$', views.employee_new, name='employee_new'),
    url(r'^employee/(?P<pk>\d+)/edit/$', views.employee_edit, name='employee_edit'),
    url(r'^admin/detail/$', views.admin_edit, name='admin_detail'),
    url(r'^employee/add/$', views.add_employee, name='add_employee'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate')
]

company/models.py
from django.db import models

class Company(models.Model):
    '''
    Company model stores details of company
    '''
    name = models.CharField(max_length = 250,unique=True)
    logo = models.ImageField(upload_to = 'payroll',
                                    default = 'None/payroll_logo.png'
                             )
    address_line_1 = models.CharField(max_length = 200)
    address_line_2 = models.CharField(max_length = 200)
    state = models.CharField(max_length = 200)
    postal_code = models.IntegerField(default = 0000)
    country = models.CharField(max_length = 200)
    fax = models.CharField(max_length = 17)
    website = models.CharField(max_length = 200,unique=True)

    def publish(self):
        self.save()
        
    def __str__(self):
        return self.name

    
class Holiday(models.Model):
    '''
    Holiday models stores date for all holiday falling in a year
    '''
    company = models.ForeignKey(Company, blank=True, null=True)    
    date = models.DateField()
    NAME_CHOICES = (('RD','Republic Day'),
                    ('MSHIV','Maha Shivaratri'),
                    ('HOLI','Holi'),
                    ('RM','Rama Navami'),
                    ('MJ','Mahavir Jayanti'),
                    ('GF','Good Friday'),
                    ('BP','Buddha Purnima'),
                    ('IDF',"Idu'l Fitr"),
                    ('ID','Independence Day'),
                    ('IDZ','Id-ul-Zuha(Bakrid)'),
                    ('JN','Janmashtarni (Vaishnav)'),
                    ('GC','Ganesh Chaturthi/Vinayaka Chaturthi'),
                    ('MUH','Muharram/Ashura'),
                    ('MGJ','Mahatma Gandhi Jayanti'),
                    ('DUS','Dussehra'),
                    ('DIW','Diwali (Deepavali)'),
                    ('ID','Id-e- Milad (birthday of Prophet Mohammad)'),
                    ('GN',"Guru Nanak's Birthday"),
                    ('CD','Christmas Day'),
                    ('Nd','New Year Day'),
                    ('MSANK','Makar Sankranti')
    )
    name = models.CharField(max_length=200,choices=NAME_CHOICES)

    def publish(self):
        self.save()
        
    def __str__(self):
        return self.name

    
class Work_Type(models.Model):
    '''
    Work_Type model customises the work structure for particular company
    '''
    company = models.ForeignKey(Company, blank = True, null = True)
    WORK_TYPE_CHOICES = (('SH','Saturday Halfday'),
                         ('SW','Saturday Working'),
                         ('SSH','Saturday-Sunday Holiday')
                        )
    worktype = models.CharField(max_length = 200,choices=WORK_TYPE_CHOICES)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.worktype

    
class Designation(models.Model):
    '''
    designation model stores designations for particular company
    '''
    company = models.ForeignKey(Company,
                                blank = True,
                                null = True
                               )
    
    DESIGNATION_CHOICES = (('CTO','Chief Technology Officer'),
                           ('CMO','Chief Marketing Officer'),
                           ('CAO','Chief Accounting Officer'),
                           ('CLO','Chief Legal Officer'),
                           ('CEO','Chief Executive Manager'),
                           ('SD','Senior Developer'),
                           ('JD','Junior Developer'),
                           ('HRM','Human Resource Manager'),
                           ('INT','INTERN'),
                          
                          )
    designation = models.CharField(max_length = 200,choices=DESIGNATION_CHOICES)
    privilege_leave = models.IntegerField(default = 0)
    casual_leave = models.IntegerField(default = 0)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.designation


class Department(models.Model):
    '''
    department model stores department details for particular company
    '''
    company = models.ForeignKey(Company,
                                blank=True,
                                null=True
                               )
    DEPARTMENT_CHOICES = (('PROD','Production'),
                          ('DEV','Development'),
                          ('RND','Research and Development'),
                          ('HRM','Human Resource Management'),
                          ('MRK','Marketing'),
                          ('ANF','Accounting and Finance' )
                          

                         )
    department = models.CharField(max_length = 200, choices=DEPARTMENT_CHOICES)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.department

    
class Job_Type(models.Model):
    '''
    Job_Type model stores job_type details applicable for particular company
    '''
    company = models.ForeignKey(Company,
                                blank = True,
                                null = True)
    JOB_TYPE_CHOICES = (('PROB','Probation'),
                        ('PER','Permanent Employee'),
                        ('TEM','Temporary Employee')
                       )
    jobtype = models.CharField(max_length=200, choices=JOB_TYPE_CHOICES, default='PE')

    def publish(self):
        self.save()

    def __str__(self):
        return self.jobtype

    

company/forms.py
from django import forms
from .models import Company
from .models import Holiday
from .models import Work_Type
from .models import Department
from .models import Designation
from .models import Job_Type
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# class SignUpForm(UserCreationForm):

    
#     class Meta:
#         model = User
#         fields = ('username', 'password1', 'password2', )
#     def __init__(self, *args, **kwargs):
#         company_id = kwargs.pop('company_id','')
#         super(SignUpForm, self).__init__(*args, **kwargs)
#         self.fields['company']=forms.ModelChoiceField(queryset=Company.objects.filter(company=company_id))

class DateInput(forms.DateInput):
        input_type = 'date'

class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ('name',
                  'address_line_1',
                  'address_line_2',
                  'state',
                  'postal_code',
                  'country',
                  'fax',
                  'website',
                  'logo'
                )
        
        widgets = {
            'name':forms.TextInput(attrs={'class': 'form-control','placeholder':'Company Name'}),
            'address_line_1':forms.TextInput(attrs={'class': 'form-control','placeholder':'Line 1'}),
            'address_line_2':forms.TextInput(attrs={'class': 'form-control','placeholder':'Line 2'}),
            'state':forms.TextInput(attrs={'class': 'form-control','placeholder':'State'}),
            'postal_code':forms.NumberInput(attrs={'class': 'form-control','placeholder':'Postal Code'}),
            'country':forms.TextInput(attrs={'class': 'form-control','placeholder':'Country'}),
            'fax':forms.NumberInput(attrs={'class': 'form-control','placeholder':'Fax'}),
            'website':forms.URLInput(attrs={'class': 'form-control','placeholder':'Website'}),
            'logo':forms.ClearableFileInput(attrs={'class': 'form-control','placeholder':'Profile Picture'})
                }
    def clean_name(self):
        name=self.cleaned_data['name']
        if name is None:
            raise forms.ValidationError('Invalid Name',code="name")
        return name
    
class HolidayForm(forms.ModelForm):

    class Meta:

        model = Holiday
        fields = ('company',
                  'date',
                  'name'
        )
        widgets = {
            'company':forms.Select(attrs={'class': 'form-control','placeholder':'Company'}),
            'date':DateInput(attrs={'class': 'form-control','placeholder':'date'}),
            'name':forms.Select(attrs={'class': 'form-control','placeholder':'Holiday'}),
        }
        def clean_name(self):
            print("in clean method")
            name = self.cleaned_data['name']
            if Holiday.objects.filter(name=name).exists():
                print("validation error raised")
                raise forms.ValidationError("This name already exist.")
            return name
class WorkTypeForm(forms.ModelForm):

    class Meta:
        
        model = Work_Type
        fields = ('company',
                  'worktype'
        )
        widgets = {
            'company':forms.Select(attrs={'class': 'form-control','placeholder':'Company'}),
            'worktype':forms.Select(attrs={'class': 'form-control','placeholder':'Work Type'}),
            
                  }
        
class DesignationForm(forms.ModelForm):

    class Meta:
        
        model = Designation
        fields = ('company',
                  'designation',
                  'privilege_leave',
                  'casual_leave'
        )
        widgets = {
            'company':forms.Select(attrs={'class': 'form-control','placeholder':'Company'}),
            'designation':forms.Select(attrs={'class': 'form-control','placeholder':'Designation'}),
            'privilege_leave':forms.NumberInput(attrs={'class': 'form-control','placeholder':'Privilege Leave'}),
            'casual_leave':forms.NumberInput(attrs={'class': 'form-control','placeholder':'Privilege Leave'}),
        }
        
class DepartmentForm(forms.ModelForm):

    class Meta:

        model = Department
        fields = ( 'company',
                   'department'
        )
        widgets = {
            'company':forms.Select(attrs={'class': 'form-control','placeholder':'Company'}),
            'department':forms.Select(attrs={'class': 'form-control','placeholder':'Department'}),
        }
        
class JobTypeForm(forms.ModelForm):
    class Meta:

        model = Job_Type
        fields = ('company',
                  'jobtype'
        )
        widgets = {
            'company':forms.Select(attrs={'class': 'form-control','placeholder':'Company'}),
            'jobtype':forms.Select(attrs={'class': 'form-control','placeholder':'Job Type'}),
        }

company/templates/company/.#home.html
jibiya@jibiya-Inspiron-3542.3637:1529730227

company/templates/company/department_detail.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Department Details</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_department'  %}">Department</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>


<table class="table ">
    <thead class="thead-dark">
        <tr>

            <th scope="col">Department</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for record in dept %}



            <td>{{record.get_department_display}}</td>
            <td><a class="btn btn-light" href= "{% url 'department_delete' pk=record.pk  %}">Delete</a></td>
        </tr>
        <tbody>
            {% endfor %}
</table>






{% endblock %}

company/templates/company/department_edit.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Add Department</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_department'  %}">Department</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>

<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}

    <form method="POST" class="employee-form">{% csrf_token %}


        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    {{ form.department.errors }}
                    {{ form.department.label_tag }}
                    {{ form.department }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-sm" name="btnCompany">Add</button>



{% if dept%}
<div class="row mt-4">
    <div class="col">
        <table class="table table-md" style="width: 80.66%">
            <thead class="thead-dark">
                <tr>

                    <th scope="col">Holiday Name</th>
                    <th  scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for record in dept %}



                    <td>{{record.get_department_display}}</td>
                    <td><a class="btn btn-light" href= "{% url 'department_delete' pk=record.pk  %}">Delete</a></td>
                </tr>
                <tbody>

                    {% endfor %}
        </table>
    </div>
</div>
{% endif %}




{% endblock %}

company/templates/company/designation_detail.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Designation Details</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_department'  %}">Department</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>


<table class="table ">
    <thead class="thead-dark">
        <tr>

            <th scope="col">Designation</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for record in desg %}



            <td>{{record.get_designation_display}}</td>
            <td><a class="btn btn-light" href= "{% url 'designation_delete' pk=record.pk  %}">Delete</a></td>
        </tr>
        <tbody>
            {% endfor %}
</table>






{% endblock %}

company/templates/company/designation_edit.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Add Designation</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_department'  %}">Department</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>

<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}




    <form method="POST" class="employee-form">{% csrf_token %}

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    {{form.designation.errors }}
                    {{form.designation.label_tag }}
                    {{form.designation }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    {{form.privilege_leave.errors }}
                    {{form.privilege_leave.label_tag }}
                    {{form.privilege_leave }}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    {{form.casual_leave.errors }}
                    {{form.casual_leave.label_tag }}
                    {{form.casual_leave }}
                </div>
            </div>
        </div>


        <button type="submit" class="btn btn-primary btn-sm" name="btndesignation">Add</button>



{% if desg %}
<div class="row mt-4">
    <div class="col">
        <table class="table table-md" style="width: 80.66%">
            <thead class="thead-dark">
                <tr>

                    <th scope="col">Holiday Name</th>
                    <th  scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for record in desg %}



                    <td>{{record.get_designation_display}}</td>
                    <td><a class="btn btn-light" href= "{% url 'designation_delete' pk=record.pk  %}">Delete</a></td>
                </tr>
                <tbody>

                    {% endfor %}
        </table>
    </div>
</div>
{% endif %}


{% endblock  %}

company/templates/company/holiday_detail.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Holiday Details</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_department'  %}">Department</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>


<table class="table ">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Holiday Name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for record in holiday %}


                 <th scope="row">{{record.date}}</th>
                 <td>{{record.get_name_display}}</td>
                 <td><a class="btn btn-light" href= "{% url 'holiday_delete' pk=record.pk  %}">Delete</a></td>
                 </tr>
                 <tbody>
                 {% endfor %}
</table>






{% endblock %}

company/templates/company/holiday_edit.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Add Holiday </h1>
<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_department'  %}" >Department</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>
<div class="row">
    <div class="col-sm-7">
        {% for message in messages %}
        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>

            {{ message }}

        </div>
        {% endfor %}


        {{form.non_field_errors}}

        <form method="POST" class="employee-form">{% csrf_token %}

            <!-- {{form.company.errors }}
                 {{form.company.label_tag }}
                 {{form.company }}
               -->
            <div class="row">
                <div class="col" id="holiday_name">
                    <div class="form-group">
                        {{form.name.errors }}
                        {{form.name.label_tag }}
                        {{form.name }}
                    </div>
                </div>
                <div class="col" id="holiday_date">
                    <div class="form-group">
                        {{form.date.errors }}
                        {{form.date.label_tag }}
                        {{form.date }}
                    </div>
                </div>
            </div>

<div class="row justify-content-center">
            <button type="submit" class="btn btn-primary btn-md " name="btnCompany">Add</button>
</div>

    </div>

</div>
{% if holiday_list %}
<div class="row mt-4">
    <div class="col">
        <table class="table table-md" style="width: 80.66%">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Holiday Name</th>
                    <th  scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for record in holiday_list %}


                    <th scope="row">{{record.date}}</th>
                    <td>{{record.get_name_display}}</td>
                    <td><a class="btn btn-light" href= "{% url 'holiday_delete' pk=record.pk  %}">Delete</a></td>
                </tr>
                <tbody>

                    {% endfor %}
        </table>
    </div>
</div>
{% endif %}


{% endblock  %}

company/templates/company/jobtype_detail.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Job-Type Details</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_department'  %}">Department</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>


<table class="table ">
    <thead class="thead-dark">
        <tr>

            <th scope="col">Job-Type</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for record in jobtype %}



            <td>{{record.get_jobtype_display}}</td>
            <td><a class="btn btn-light" href= "{% url 'jobtype_delete' pk=record.pk  %}">Delete</a></td>
        </tr>
        <tbody>
            {% endfor %}
</table>






{% endblock %}

company/templates/company/jobtype_edit.html
{% extends 'company/base.html' %}
{%include 'login/messages.html' %}
{% block content %}

<h1>Add Job-Type</h1>

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'edit_company'  %}">Company</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_holiday'  %}">Holiday</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_department'  %}">Department</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="{% url 'add_designation'  %}">Designation</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_worktype'  %}">Work-Type</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active " href="{% url 'add_jobtype'  %}">Job-Type</a>
        </li>
    </ul>
</div>

</div>

<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}

    <form method="POST" class="employee-form">{% csrf_token %}



        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    {{ form.jobtype.errors }}
                    {{ form.jobtype.label_tag }}
                    {{ form.jobtype }}
                </div>
            </div>

            </div>
<button type="submit" class="btn btn-primary btn-sm" name="btnJobType">Add</button>

{% if jobtype%}
<div class="row mt-4">
    <div class="col">
        <table class="table table-md" style="width: 80.66%">
            <thead class="thead-dark">
                <tr>

                    <th scope="col">Work-Type</th>
                    <th  scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for record in jobtype %}



                    <td>{{record.get_jobtype_display}}</td>
                    <td><a class="btn btn-light" href= "{% url 'jobtype_delete' pk=record.pk  %}">Delete</a></td>
                </tr>
                <tbody>

                    {% endfor %}
        </table>
    </div>
</div>



{% endif %}
        {% endblock %}