mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user.urls')),
    url(r'', include('login.urls')),
    url(r'', include('payroll.urls')),
    url(r'', include('company.urls')),
    url(r'', include('attendance.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.conf.urls import url
from . import views
# from payroll.views import Pdf


urlpatterns = [
       url(r'^salary/month-year/(?P<pk>\d+)/$', views.salary_monthyear, name='salary_monthyear'),
       url(r'^salary/(?P<pk>\d+)/(?P<monthyear>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$', views.salary_detail, name='salary_detail'),
       url(r'^salary-slip/(?P<pk>\d+)/$', views.salary_slip, name='salary_slip'),
    url(r'^salary/report/(?P<pk>\d+)/pdf/$',views.report_salary_pdf, name='report_salary_pdf'),
    url(r'^salary/(?P<pk>\d+)/pdf/$',views.salary_pdf, name='salary_pdf'),
    
       url(r'^update-salary/(?P<pk>\d+)/$', views.update_salary, name='update_salary'),
       url(r'^update-salary/$', views.update_salary, name='update_salary'),
       url(r'^salary/view/$',views.salary_report,name='view_salary'),
       url(r'^salary/employee-list/$',views.salary_employee_list,name='salary_employee_list'),
       url(r'^salary/pending-list/$',views.salary_pending_list,name='salary_pending_list'),
    url(r'^salary/appraisal/$',views.salary_increment,name='salary_increment'),
    url(r'^salary/appraisal-list/$',views.salary_increment_list,name='salary_increment_list')
    
]

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^employee/list$', views.employee_list, name='employee_list'),
    url(r'^employee/(?P<pk>\d+)/$', views.employee_detail, name='employee_detail'),
    url(r'^employee/new/$', views.employee_new, name='employee_new'),
    url(r'^employee/(?P<pk>\d+)/edit/$', views.employee_edit, name='employee_edit'),
    url(r'^admin/detail/$', views.admin_edit, name='admin_detail'),
    url(r'^employee/add/$', views.add_employee, name='add_employee'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate')
]

company/models.py
from django.db import models

class Company(models.Model):
    '''
    Company model stores details of company
    '''
    name = models.CharField(max_length = 250,unique=True)
    logo = models.ImageField(upload_to = 'payroll',
                                    default = 'None/payroll_logo.png'
                             )
    address_line_1 = models.CharField(max_length = 200)
    address_line_2 = models.CharField(max_length = 200)
    state = models.CharField(max_length = 200)
    postal_code = models.IntegerField(default = 0000)
    country = models.CharField(max_length = 200)
    fax = models.CharField(max_length = 17)
    website = models.CharField(max_length = 200,unique=True)

    def publish(self):
        self.save()
        
    def __str__(self):
        return self.name

    
class Holiday(models.Model):
    '''
    Holiday models stores date for all holiday falling in a year
    '''
    company = models.ForeignKey(Company, blank=True, null=True)    
    date = models.DateField()
    NAME_CHOICES = (('RD','Republic Day'),
                    ('MSHIV','Maha Shivaratri'),
                    ('HOLI','Holi'),
                    ('RM','Rama Navami'),
                    ('MJ','Mahavir Jayanti'),
                    ('GF','Good Friday'),
                    ('BP','Buddha Purnima'),
                    ('IDF',"Idu'l Fitr"),
                    ('ID','Independence Day'),
                    ('IDZ','Id-ul-Zuha(Bakrid)'),
                    ('JN','Janmashtarni (Vaishnav)'),
                    ('GC','Ganesh Chaturthi/Vinayaka Chaturthi'),
                    ('MUH','Muharram/Ashura'),
                    ('MGJ','Mahatma Gandhi Jayanti'),
                    ('DUS','Dussehra'),
                    ('DIW','Diwali (Deepavali)'),
                    ('ID','Id-e- Milad (birthday of Prophet Mohammad)'),
                    ('GN',"Guru Nanak's Birthday"),
                    ('CD','Christmas Day'),
                    ('Nd','New Year Day'),
                    ('MSANK','Makar Sankranti')
    )
    name = models.CharField(max_length=200,choices=NAME_CHOICES)

    def publish(self):
        self.save()
        
    def __str__(self):
        return self.name

    
class Work_Type(models.Model):
    '''
    Work_Type model customises the work structure for particular company
    '''
    company = models.ForeignKey(Company, blank = True, null = True)
    WORK_TYPE_CHOICES = (('SH','Saturday Halfday'),
                         ('SW','Saturday Working'),
                         ('SSH','Saturday-Sunday Holiday')
                        )
    worktype = models.CharField(max_length = 200,choices=WORK_TYPE_CHOICES)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.worktype

    
class Designation(models.Model):
    '''
    designation model stores designations for particular company
    '''
    company = models.ForeignKey(Company,
                                blank = True,
                                null = True
                               )
    
    DESIGNATION_CHOICES = (('CTO','Chief Technology Officer'),
                           ('CMO','Chief Marketing Officer'),
                           ('CAO','Chief Accounting Officer'),
                           ('CLO','Chief Legal Officer'),
                           ('CEO','Chief Executive Manager'),
                           ('SD','Senior Developer'),
                           ('JD','Junior Developer'),
                           ('HRM','Human Resource Manager'),
                           ('INT','INTERN'),
                          
                          )
    designation = models.CharField(max_length = 200,choices=DESIGNATION_CHOICES)
    privilege_leave = models.IntegerField(default = 0)
    casual_leave = models.IntegerField(default = 0)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.designation


class Department(models.Model):
    '''
    department model stores department details for particular company
    '''
    company = models.ForeignKey(Company,
                                blank=True,
                                null=True
                               )
    DEPARTMENT_CHOICES = (('PROD','Production'),
                          ('DEV','Development'),
                          ('RND','Research and Development'),
                          ('HRM','Human Resource Management'),
                          ('MRK','Marketing'),
                          ('ANF','Accounting and Finance' )
                          

                         )
    department = models.CharField(max_length = 200, choices=DEPARTMENT_CHOICES)
    
    def publish(self):
        self.save()

    def __str__(self):
        return self.department

    
class Job_Type(models.Model):
    '''
    Job_Type model stores job_type details applicable for particular company
    '''
    company = models.ForeignKey(Company,
                                blank = True,
                                null = True)
    JOB_TYPE_CHOICES = (('PROB','Probation'),
                        ('PER','Permanent Employee'),
                        ('TEM','Temporary Employee')
                       )
    jobtype = models.CharField(max_length=200, choices=JOB_TYPE_CHOICES, default='PE')

    def publish(self):
        self.save()

    def __str__(self):
        return self.jobtype

    

payroll/models.py
import decimal
import datetime
import calendar
from django.db import models
from django.db.models import When, F, Q
from django.utils import timezone
from django.core.validators import RegexValidator
from calendar import weekday, monthrange, SUNDAY ,SATURDAY


class Salary(models.Model):
    '''
    Salary details accepts allowance and deductions details and 
    calculates gross earnings, gross deeductions and net salary
    '''
    employee = models.ForeignKey("user.Employee",
                               related_name = '+',
                               blank = True,
                               null = True
                              )
    
    date = models.DateField()
    month_year = models.DateField(blank=True)
    basic_percentage = models.FloatField(default = 35)
    basic_amount=models.FloatField(default = 0)
    hra_amount=models.FloatField(default = 0)
    hra_percentage = models.FloatField(default = 40)
    conveyance_allowance = models.IntegerField(default = 1600)
    special_allowance = models.IntegerField(default = 0)
    bonus = models.IntegerField(default=0)
    proffessional_tax = models.IntegerField(default = 200)
    income_tax = models.IntegerField(default = 0)
    loss_of_pay = models.DecimalField(max_digits = 10,
                                      decimal_places = 3,
                                      default=decimal.Decimal('0000000.000')
                                 )
    gross_earning = models.DecimalField(max_digits = 10,
                                      decimal_places = 2,
                                      default = decimal.Decimal('0000000.000')
                                     )
    gross_deduction = models.DecimalField(max_digits = 6,
                                        decimal_places = 2,
                                        default = decimal.Decimal('0000.00')
                                       )
    
    total_days = models.IntegerField(default = 25)
    weekend = models.IntegerField(default = 8)
    public_holidays = models.IntegerField(default = 0)
    working_days=models.IntegerField(default = 22)
    attendance=models.IntegerField(null=True)
    net_salary=models.DecimalField(max_digits = 10,
                                   decimal_places = 3,
                                   default = decimal.Decimal('0000000.000')
                                  )
    
    
    def publish(self):
        
        self.save()
    def __str__(self):
         return self.employee.user.username

user/models.py
import decimal
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Employee(models.Model):
    '''
    Employee model stores all the details of employee required for Payroll System
 
    '''
    company = models.ForeignKey('company.Company',
                                 null=True,
                                 blank=True
                                )
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                null=True
                                )
    
    name = models.CharField(max_length = 50,null=True)
    address = models.TextField()
    phone_regex = RegexValidator(regex = r'^\+?1?\d{9,15}$',
                                 message = "Phone number must be entered in format :'+999999999'. "
                                )
    contact = models.CharField(validators = [phone_regex],
                               max_length = 17
                              )
    alter_Contact = models.CharField(validators = [phone_regex],
                                     max_length=17
                                    )
    emailid = models.EmailField(null=True)
    office_emailid = models.EmailField(null=True,blank=True)
    GENDER_CHOICES = (('M', 'Male'),
                      ('F', 'Female'),
                     )
    gender = models.CharField(max_length = 20,
                              choices = GENDER_CHOICES,
                              default = "Select"
                             )
    Dob = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to = 'payroll',
                                    default = 'None/no-img.jpeg'
    )
    joining_date = models.DateField(blank = True,
                                    null = True
                                   )
    job_type = models.CharField(max_length = 15,
                                blank = True,
                                null=True
                               )
    job_location = models.CharField(max_length = 50,
                                    blank = True,
                                    null=True
                                   )
    probation_period = models.IntegerField(blank = True,
                                           null=True
                                          )
    is_admin = models.BooleanField(default=False)


        
    def __str__(self):
        return str(self.user)


    
class Designation_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    designation = models.ForeignKey('company.Designation',
                                  blank = True,
                                  null = True
                                 )
    date = models.DateField()
    
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.designation.designation+" " +str(self.employee)

    
class Department_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    department = models.ForeignKey('company.Department',
                                 blank = True,
                                 null = True
                                )
    date = models.DateField()

    def publish(self):
        self.save()

    def __str__(self):
        return self.department.department


    
class Job_Type_History(models.Model):
    '''
    Designation_History model  records designation_history for particular employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
                                )
    job_type = models.ForeignKey('company.Job_Type',
                                 blank = True,
                                 null = True
                                )
    date=models.DateField()

    def publish(self):
        self.save()

    def __str__(self):
        return self.job_type.jobtype


class Leave_History(models.Model):
    
    '''
    Leave_History records total leaves taken by an employee
    '''
    employee = models.ForeignKey(Employee,
                                 blank = True,
                                 null = True
    )
    work_type = models.ForeignKey("company.Work_Type",
                                  blank = True,
                                  null = True
    )
    attendance = models.ForeignKey("attendance.Attendance",
                                   blank = True,
                                   null = True
    )
    leave_type = models.CharField(max_length = 200,
                                  default = "None"
    )
    date=models.DateField()
   
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.employee.name+"Leave History"

    
class Salary_History(models.Model):
    '''
    Salary_History records Salary details of an employee
    '''
    employee = models.ForeignKey(Employee,
                                 related_name = '+',
                                 blank = True,
                                 null = True
                                )
    date = models.DateField()                           
    basic_percentage = models.FloatField(default = 35)
    hra_percentage = models.FloatField(default = 40)
    conveyance_allowance = models.IntegerField(default = 1600)
    proffessional_tax = models.IntegerField(default = 200)
    income_tax = models.IntegerField(default = 0)
    
    def publish(self):
        self.save()

class Salary_Increment(models.Model):
    '''
    Salary_Increment records salary-increment details of an employee
    '''
    date = models.DateField()
    employee = models.ForeignKey(Employee,
                                 related_name = '+',
                                 blank = True,
                                 null = True
                                )
    salary = models.DecimalField(max_digits = 10,
                               decimal_places = 3,
                                 default = decimal.Decimal('0000000.000'),
                                 blank=True
                              
                              )
    effective_from = models.DateField(blank=True)
    def publish(self):
        self.save()
        
    def __str__(self):
        return self.employee.user.username+" "+str(self.effective_from)

user/templates/payroll/acc_active_email.html
<!-- {% autoescape off %} -->
<h4>Hello {{ salary.employee.name }},</h4><br><br>
<h5><p>Attached is payslip for {{salary.month_year}} from {{company.name}}</p></h5><br><br><br><br>
<h5>Thanks & Regards,
{{admin.name}},
{{dept.department.get_department_display}}-{{desgn.designation.get_designation_display}}
<img src={{company.logo.url}}></img>{{company.name}}</h5>
<!-- {% endautoescape %} -->

user/templates/payroll/employee_base.html
{% load staticfiles %}


<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ request.user.employee.company.logo.url}}">

        <title>Payroll For {{ request.user.employee.company.name }}     </title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'user/dist/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'user/dashboard.css' %}" rel="stylesheet">
    </head>

    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">


            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
                <img src="{{request.user.employee.company.logo.url}}" width="30" height="30" class="d-inline-block align-left" alt="">
                                 {% if user.is_authenticated %}
                {{ request.user.employee.company.name }}
                {% endif  %}
                  </a>

                  <!--
                       <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"></a> -->
            <!-- {{ request.session.company }} -->
            <!--input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"-->
            <ul class="navbar-nav px-3 ">
                 <li class="nav-item text-nowrap">


                    {% if user.is_authenticated %}
                    <p class="pt-3 nav-link active d-inline ">Logged in as <strong class="alert">{{ user.username }}</strong> <a class="nav-link" href="{% url 'logout' %}">Sign out</a></p>

                    {% endif  %}
                </li>

            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">

                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link " href="#">
                                    <span data-feather="home"></span>
                                    Dashboard <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link " href="{% url 'edit_company'  %}">
                                    <span data-feather="users"></span>
                                    Company
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="attendance.html">
                                    <span data-feather="users"></span>
                                    Attendance
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <span data-feather="dollar-sign"></span>
                                    Salary
                                </a>
                            </li>

                        </ul>


                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">



            {% block content %}
            {% endblock %}
</form>

                    </div>
            </div>
</html>

user/templates/payroll/employee_detail.html
{% extends 'payroll/user/base.html' %}
{%include 'payroll/messages.html' %}
{% block content %}

{% if employee.is_admin == True  %}
<h1>Admin Profile</h1>
{% else %}
<h1>Employee Profile</h1>
{% endif %}

<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">



     <li class="nav-item">
     <a class="nav-link" href="{% url 'add_employee'  %}">Add Employee</a>
     </li>

     <li class="nav-item">
     <a class="nav-link" href="{% url 'employee_list'  %}" >View All Employee</a>
     </li>

     <li class="nav-item">
     <a class="nav-link active" href="{% url 'admin_detail'  %}">Update Admin Profile</a>
     </li>



     </ul>
     </div>






</div>
<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}
</div>

    <div class="row border-bottom mb-md-2 ">
        <div class="col">
            <img  src="{{ employee.profile_pic.url  }}" width=150px height=150px>
            <p><h4>Name: {{employee.name}}</h></p>

        </div>
        <div class="col">
            <div class="form-group text-left">
                <!-- <img  src="{{ employee.profile_pic.url  }}" width=150px height=150px> -->
            </div>
        </div>
        <!-- <div class="col"> --> <!-- <a class="btn btn-default" href="{% url 'employee_edit' pk=employee.pk %}">Edit</a><span class="glyphicon glyphicon-pencil"></span></a> -->


        <div class="col">
            <div class="form-group text-left">

                <div class="dropdown">
                    <Button type="button"  id="dropdown-toggle" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown">Action</Button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item"  href={% url 'employee_edit' pk=employee.pk  %}>Edit</a>
                        <a class="dropdown-item" href="{% url 'mark_attendance' pk=employee.pk  %}">Attendance</a>
                        <a class="dropdown-item" href="{% url 'update_salary' pk=employee.pk  %}">Update Salary</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="alert alert-light border" role="alert"><h6>Personal Details :</h6></div>
    <div class= "row">

        <div class="col border ">
            <div class="table-responsive-sm">
                <table class="table table-md">
                    <tr>
                        <td style="width: 16.66%">Address:</td>
                        <td >
                            <address>
                                {{employee.address }}
                            </address>
                        </td>

                    </tr>
                    <tr>
                        <td style="width: 16.66%">Contact:</td>
                        <td>{{employee.contact}}</td>
                    </tr>
                    <tr>
                        <td style="width: 16.66%">Alternate Contact:</td>
                        <td>{{employee.alter_Contact}}</td>
                    </tr>

                    <tr>
                        <td style="width: 16.66%">Email ID:</td>
                        <td>{{employee.emailid}}</td>
                    </tr>
                    <tr>
                        <td style="width: 16.66%">Office Email ID:</td>
                        <td>{{employee.office_emailid}}</td>
                    </tr>
                    <tr>
                        <td style="width: 16.66%">Gender:</td>
                        <td>{{employee.get_gender_display}}</td>
                    </tr>
                    <tr>
                        <td style="width: 16.66%">Date-Of-Birth:</td>
                        <td>{{employee.Dob}}</td>
                    </tr>
                    <tr>
                        <td style="width: 16.66%">Joining Date:</td>
                        <td>{{employee.joining_date}}</td>
                    </tr>

                    <table>
            </div>
        </div>



    <div class="alert alert-light border" role="alert"><h6>Job Profile :</h6></div>

    <!-- <div class= "row p-2"> -->

        <div class="col border">
            <div class="table-responsive-sm">
                <table class="table table-md">
                    <tr>
                        <td style="width: 16.66%">Designation:</td>
                        {% if desgn == None %}
                        <td>

                                <strong class="text-danger font-italic">Designation not added</strong>

                        </td>
                        {% else%}
                        <td>

                                {{desgn.designation.get_designation_display }}

                        </td>
                        {% endif %}

                    </tr>
                    <tr>
                        <td style="width: 16.66%">Department:</td>
                        {% if dept == None %}
                        <td>

                                <strong class="text-danger font-italic">Department not added</strong>

                        </td>
                        {% else %}
                        <td>{{dept.department.get_department_display}}</td>
                        {% endif %}
                    </tr>

                    <tr>
                        <td style="width: 16.66%">Job-Type:</td>
                        {% if jobtype == None %}
                        <td>

                                <strong class="text-danger font-italic">Job-Type not added</strong>

                        </td>
                        {% else %}

                        <td>{{jobtype.job_type.get_jobtype_display}}</td>
                        {% endif %}
                    </tr>


                    <!-- <tr>
                         <td style="width: 16.66%">Salary:</td>
                         <td>{{employee.salary}}</td>
                         </tr> -->

                    <table>
            </div>
        </div>

        <div class="alert alert-light border" role="alert"><h6>Salary Structure :</h6></div>

        <div class="col border">

{% if salary == None %}
                <strong class="text-danger font-italic">Salary structure not added</strong>
                {% else %}

            <div class="table-responsive-sm">
                <table class="table table-md">
                    <tr>
                        <td style="width: 16.66%">Annual Salary :</td>
                        <td>{{annual_salary.salary}}</td>
                    </tr>
                    <tr>
                        <td colspan=2 style="width: 16.66%"><strong>Allowance:</strong></td>
                        <td colspan=2 style="width: 16.66%"><strong>Deduction:</strong></td>

                    </tr>
                    <tr>
                        <td style="width: 16.66%">Basic Percentage</td>
                        <td>{{salary.basic_percentage}}</td>
                        <td style="width: 16.66%">Professional Tax</td>
                        <td>{{salary.proffessional_tax}}</td>
                    </tr>

                                     <tr>
                        <td style="width: 16.66%">Hra Percentage</td>
                        <td>{{salary.hra_percentage}}</td>
                        <td style="width: 16.66%">Income Tax</td>
                        <td>{{salary.income_tax}}</td>
                                     </tr>
                                      <tr>
                        <td style="width: 16.66%">Conveyance Allowance</td>
                        <td>{{salary.conveyance_allowance}}</td>

                                      </tr>

    </div>

{% endif %}

            </div>

    {% endblock  %}

user/templates/payroll/employee_list.html
{% extends 'payroll/user/base.html' %}
{%include 'payroll/messages.html' %}
{% block content %}

<h1>Employee List</h1>


<div class="btn-toolbar mb-2 mb-md-0">
    <ul class="nav nav-tabs">



        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_employee'  %}">Add Employee</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'employee_list'  %}" >View All Employee</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="{% url 'admin_detail'  %}">Update Admin Profile</a>
        </li>



    </ul>
</div>




</div>

<div class="col-sm-7">
    {% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>

        {{ message }}

    </div>
    {% endfor %}

    <div class="employee">

        <div class="row">
            {% for record in emp %}



            <div class="col-md-4 border pb-5">
                <p> <a href="{% url 'employee_detail' pk=record.pk %}">Name: {{ record.user.username }} </a><span></span>  </p>
                <div class="image">
                    <img src='{{record.profile_pic.url}}' class="image" alt="Cinque Terre"alt="No image" height="150" width="100%"border="5"></td></div>
            </div>

            {% endfor  %}
        </div>



        <!-- <div class="table-responsive-sm">
             <table class="table table-sm">


             <thead>
             <tr>
             <th  class="text-center"> <strong ></strong></th>
             <th  class="text-center"> <strong ></strong></th>


             </tr>
             </thead>




             {% for record in emp %}
             <tr><td>

             <p> <a href="{% url 'employee_detail' pk=record.pk %}">Name: {{ record.user.username }} </a> </p>
             <div class="image">
             <img src='{{record.profile_pic.url}}' class="img-circle" alt="Cinque Terre"alt="No image" height="20%" width="20%"border="5"></td></div>


             {% endfor %}

             </tbody>
             </table>
             </div> -->


    </div>
</div>
</div>
{% endblock %}